language: android
jdk: oraclejdk8
sudo: require

env:
  global:
    # wait up to 20 minutes for adb to connect to emulator
    - ADB_INSTALL_TIMEOUT=20

android:
  components:
    - platform-tools		
    - tools
    - build-tools-23.0.3
    - android-22
    - android-23
    - sys-img-armeabi-v7a-android-23
    - extra-android-m2repository
    - compile 'com.google.android.gms:play-services:8.4.0'
    - compile 'com.firebase:firebase-client-android:2.5.2'

before_script:
  # Create and start emulator
  - echo no | android create avd --force -n test -t android-23 --abi armeabi-v7a 
  - emulator -avd test -no-skin -no-audio -no-window &
  - travis_wait 20 chmod +x ./gradlew
  - chmod 777 .buildscript/launchInstrumentationTests.sh
  - android-wait-for-emulator
  - adb shell input keyevent 82 &



script:
  - ./gradlew assembleDebug -PdisablePreDex
  - ./gradlew assembleAndroidTest -PdisablePreDex
  - adb devices
  - adb install -r app/build/outputs/apk/app-debug.apk
  - adb install -r app/build/outputs/apk/app-debug-androidTest-unaligned.apk
  - ./gradlew check -PdisablePreDex --continue --stacktrace

after_success:
  - ./gradlew jacocoFullReport
  - pip install --user codecov
  - codecov
  - bash <(curl -s https://codecov.io/bash)


after_failure:
  - wget http://imgur.com/tools/imgurbash.sh
  - chmod a+x imgurbash.sh
  - adb shell screencap -p | sed 's/\r$//' &gt; screen.png
  - ./imgurbash.sh screen.png
  - pandoc builder/build/reports/tests/index.html -t plain | sed -n '/^Failed tests/,/default-package/p'
