language: android
android:
  components:
    - tools
    - tools
    - platform-tools
    - build-tools-23.0.3
    - android-23
    - extra-google-google_play_services
    - extra-google-m2repository
    - extra-android-m2repository
    - addon-google_apis-google-23

env:
  global:
    - GRADLE_OPTS="-Xms128m"

before_script:
 - chmod +x ./gradlew

script:
   - ./gradlew build connectedCheck